image: node:latest

cache:
  paths:
    - frontend/babel-preset-react-app/node_modules/
    - frontend/eslint-config-react-app/node_modules/
    - frontend/react-app-polyfill/node_modules/
    - frontend/node_modules/

pages:
  stage: build
  script:
    - cd frontend/babel-preset-react-app && yarn && cd ../../
    - cd frontend/eslint-config-react-app && yarn && cd ../../
    - cd frontend/react-app-polyfill && yarn && cd ../../
    - cd frontend/ && yarn && yarn build
  artifacts:
    paths:
      - frontend/build
    expire_in: 1 day
  publish: frontend/build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - frontend/**/*
  environment: production

