image: node:latest

cache:
  paths:
    - node_modules/

pages:
  script:
    - cd frontend/ && yarn && yarn build
  artifacts:
    paths:
      - frontend/build
  publish: frontend/build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production

